import { Event, Ticket, AttendanceNFT, User, OrganizerStats } from './types'

export const mockUser: User = {
  address: '0x719...a3b2',
  displayName: 'alice.sui',
  isConnected: true,
  loginMethod: 'zklogin',
  zkProvider: 'google',
  badges: ['Early Adopter', 'Whale', 'Builder'],
  eventsAttended: 12,
  ticketsOwned: 3,
}

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Sui Basecamp 2025',
    description: 'The flagship Sui ecosystem conference bringing together builders, creators, and visionaries from around the world. Three days of talks, workshops, and networking.',
    date: 'Apr 14, 2025',
    time: '9:00 AM - 6:00 PM CET',
    location: 'Paris, France',
    capacity: 500,
    registered: 347,
    price: 15,
    currency: 'SUI',
    image: '/events/basecamp.jpg',
    isPrivate: false,
    organizer: {
      name: 'Sui Foundation',
      address: '0x8f2...e1c9',
      verified: true,
    },
    walrusBlobId: '9x8f...a122',
    tags: ['Conference', 'Networking', 'Web3'],
    status: 'upcoming',
  },
  {
    id: '2',
    title: 'Walrus Developer Workshop',
    description: 'Hands-on workshop covering Walrus storage integration, blob management, and building decentralized applications with persistent storage.',
    date: 'Mar 28, 2025',
    time: '2:00 PM - 5:00 PM PST',
    location: 'San Francisco, CA',
    capacity: 50,
    registered: 48,
    price: 0,
    currency: 'SUI',
    image: '/events/workshop.jpg',
    isPrivate: false,
    organizer: {
      name: 'Walrus Labs',
      address: '0x3a7...b4d2',
      verified: true,
    },
    walrusBlobId: '7b2c...x891',
    tags: ['Workshop', 'Development', 'Storage'],
    status: 'upcoming',
  },
  {
    id: '3',
    title: 'DAO Strategy Meeting',
    description: 'Exclusive quarterly meeting for DAO members to discuss roadmap, treasury allocation, and governance proposals.',
    date: 'Mar 15, 2025',
    time: '10:00 AM UTC',
    location: 'Virtual (Encrypted)',
    capacity: 25,
    registered: 18,
    price: 0,
    currency: 'SUI',
    image: '/events/dao.jpg',
    isPrivate: true,
    requiredBadge: 'Whale',
    organizer: {
      name: 'SuiDAO',
      address: '0x1c9...f7e3',
      verified: true,
    },
    walrusBlobId: '4d9e...z334',
    tags: ['DAO', 'Governance', 'Private'],
    status: 'upcoming',
  },
  {
    id: '4',
    title: 'NFT Art Exhibition',
    description: 'A curated collection of digital art from the Sui ecosystem. Meet the artists, bid on exclusive pieces, and celebrate Web3 creativity.',
    date: 'Apr 5, 2025',
    time: '6:00 PM - 10:00 PM EST',
    location: 'New York, NY',
    capacity: 200,
    registered: 156,
    price: 25,
    currency: 'SUI',
    image: '/events/nft-art.jpg',
    isPrivate: false,
    organizer: {
      name: 'ArtBlocks Sui',
      address: '0x5e8...c2a1',
      verified: false,
    },
    walrusBlobId: '2a7f...k556',
    tags: ['NFT', 'Art', 'Exhibition'],
    status: 'upcoming',
  },
  {
    id: '5',
    title: 'Move Language Bootcamp',
    description: 'Intensive 2-day bootcamp covering Move smart contract development on Sui. From basics to advanced patterns.',
    date: 'May 10-11, 2025',
    time: '9:00 AM - 5:00 PM',
    location: 'Berlin, Germany',
    capacity: 30,
    registered: 30,
    price: 50,
    currency: 'SUI',
    image: '/events/bootcamp.jpg',
    isPrivate: false,
    organizer: {
      name: 'Move Academy',
      address: '0x9d4...a8f6',
      verified: true,
    },
    walrusBlobId: '8c3d...m778',
    tags: ['Education', 'Development', 'Move'],
    status: 'upcoming',
  },
  {
    id: '6',
    title: 'Sui Builder House Tokyo',
    description: 'A week-long co-working and hacking experience in Tokyo. Build, collaborate, and ship with fellow Sui developers.',
    date: 'Jun 1-7, 2025',
    time: 'All Day',
    location: 'Tokyo, Japan',
    capacity: 100,
    registered: 67,
    price: 100,
    currency: 'SUI',
    image: '/events/tokyo.jpg',
    isPrivate: false,
    organizer: {
      name: 'Sui Foundation',
      address: '0x8f2...e1c9',
      verified: true,
    },
    walrusBlobId: '1e5g...p990',
    tags: ['Hackathon', 'Builder', 'Networking'],
    status: 'upcoming',
  },
]

export const mockTickets: Ticket[] = [
  {
    id: 't1',
    ticketNumber: '0492',
    eventId: '1',
    event: mockEvents[0],
    holder: '0x719...a3b2',
    purchaseDate: 'Feb 15, 2025',
    isEncrypted: true,
    isUsed: false,
    tier: 'vip',
    walrusBlobId: '5f8a...t223',
  },
  {
    id: 't2',
    ticketNumber: '0156',
    eventId: '2',
    event: mockEvents[1],
    holder: '0x719...a3b2',
    purchaseDate: 'Mar 1, 2025',
    isEncrypted: false,
    isUsed: false,
    tier: 'general',
    secretData: {
      location: '123 Mission St, San Francisco, CA 94105',
      gateCode: 'DEV-2025',
      specialInstructions: 'Enter through the side entrance. Bring laptop.',
    },
    qrCode: 'QR_CODE_DATA_HERE',
    walrusBlobId: '3c7b...r445',
  },
  {
    id: 't3',
    ticketNumber: '0023',
    eventId: '4',
    event: mockEvents[3],
    holder: '0x719...a3b2',
    purchaseDate: 'Mar 10, 2025',
    isEncrypted: true,
    isUsed: false,
    tier: 'general',
    walrusBlobId: '9d2e...w667',
  },
]

export const mockAttendanceNFTs: AttendanceNFT[] = [
  {
    id: 'a1',
    eventId: 'past1',
    eventTitle: 'Sui Overflow Hackathon 2024',
    holder: '0x719...a3b2',
    mintedAt: 'Oct 12, 2024',
    image: '/attendance/overflow.png',
    isSoulbound: true,
    metadata: {
      checkInTime: '9:15 AM',
      verifiedBy: 'Gate Scanner #3',
    },
  },
  {
    id: 'a2',
    eventId: 'past2',
    eventTitle: 'Move Summit Singapore',
    holder: '0x719...a3b2',
    mintedAt: 'Aug 22, 2024',
    image: '/attendance/summit.png',
    isSoulbound: true,
    metadata: {
      checkInTime: '10:02 AM',
      verifiedBy: 'Manual Check-in',
    },
  },
  {
    id: 'a3',
    eventId: 'past3',
    eventTitle: 'DeFi Day London',
    holder: '0x719...a3b2',
    mintedAt: 'Jul 5, 2024',
    image: '/attendance/defi.png',
    isSoulbound: false,
    metadata: {
      checkInTime: '2:30 PM',
      verifiedBy: 'Gate Scanner #1',
    },
  },
]

export const mockOrganizerStats: OrganizerStats = {
  totalEvents: 8,
  totalTicketsSold: 1247,
  totalRevenue: 18420,
  totalCheckIns: 1089,
  averageAttendance: 87.3,
}

export const mockOrganizerEvents = mockEvents.slice(0, 3).map(event => ({
  ...event,
  analytics: {
    views: Math.floor(Math.random() * 5000) + 500,
    registrations: event.registered,
    checkIns: Math.floor(event.registered * 0.85),
    revenue: event.price * event.registered,
  }
}))


